# Generated by Django 5.2 on 2025-09-30 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_alter_usuário_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('repetir', models.BooleanField(default=False)),
                ('frequencia', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='nenhuma', max_length=20)),
                ('repeticoes', models.PositiveIntegerField(blank=True, null=True)),
                ('evento_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='eventos.eventoagenda')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_agenda', to='api.usuário')),
            ],
        ),
    ]
