# Generated by Django 5.2 on 2025-11-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_eventoagenda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoagenda',
            name='evento_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='eventos.eventoagenda'),
        ),
    ]
