# Generated by Django 5.2 on 2025-11-17 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clinica_complemento_clinica_numero'),
        ('api', '0018_rename_email_claro_usuário_email'),
        ('eventos', '0003_alter_eventoagenda_evento_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_agenda', to='accounts.clinica'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_paciente', to='api.usuário'),
        ),
    ]
