# Generated by Django 5.2 on 2025-11-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_clinica'),
        ('eventos', '0004_eventoagenda_clinica_alter_eventoagenda_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoagenda',
            name='clinica',
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_agenda', to='accounts.organizacao'),
        ),
    ]
