# Generated by Django 5.2 on 2025-12-09 16:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_eventoagenda_clinica_eventoagenda_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='exdates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='rrule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventoExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_id', models.DateField()),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], max_length=20, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('evento_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes', to='eventos.eventoagenda')),
            ],
        ),
    ]
