# Generated by Django 5.2 on 2025-11-22 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_plano_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('starter', 'Starter - Autônomos'), ('professional', 'Professional - Clínicas'), ('clinic', 'Clinic - Redes')], max_length=20, unique=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('id_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('max_pacientes', models.IntegerField()),
                ('max_usuarios', models.IntegerField()),
                ('max_avaliacoes_mes', models.IntegerField(blank=True, null=True)),
                ('recursos', models.JSONField(default=dict, help_text='Recursos disponíveis no plano')),
                ('dias_trial', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano de Pagamento',
                'verbose_name_plural': 'Planos de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='ProvedorPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('asaas', 'ASAAS'), ('stripe', 'Stripe'), ('mercadopago', 'Mercado Pago')], default='asaas', max_length=20)),
                ('api_key', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('webhook_token', models.CharField(blank=True, max_length=255)),
                ('sandbox', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Provedor de Pagamento',
                'verbose_name_plural': 'Provedores de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('id_assinatura_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim_trial', models.DateTimeField(blank=True, null=True)),
                ('data_proximo_pagamento', models.DateTimeField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('trial', 'Período de Trial'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada'), ('pendente', 'Pendente de Pagamento')], default='trial', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('credit_card', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('pix', 'PIX')], max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_pagamento', to='accounts.clinica')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.planopagamento')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.provedorpagamento')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='TransacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transacao_externo', models.CharField(max_length=100, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('received', 'Recebido'), ('overdue', 'Atrasado'), ('refunded', 'Estornado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=20, null=True)),
                ('url_boleto', models.URLField(blank=True, null=True)),
                ('codigo_pix', models.TextField(blank=True, null=True)),
                ('qrcode_pix', models.TextField(blank=True, null=True)),
                ('dados_transacao', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='pagamentos.assinatura')),
            ],
            options={
                'verbose_name': 'Transação de Pagamento',
                'verbose_name_plural': 'Transações de Pagamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('evento', models.CharField(max_length=100)),
                ('id_externo', models.CharField(blank=True, max_length=100)),
                ('processado', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamentos.provedorpagamento')),
            ],
            options={
                'verbose_name': 'Log de Webhook',
                'verbose_name_plural': 'Logs de Webhook',
                'ordering': ['-data_recebimento'],
            },
        ),
    ]
