# Generated by Django 5.2 on 2025-11-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='bandeira_cartao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='cartao_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='ultimos_digitos',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
