# Generated by Django 5.2 on 2025-11-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_assinatura_bandeira_cartao_assinatura_cartao_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('trial', 'Período de Trial'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='trial', max_length=20),
        ),
    ]
