# Generated by Django 5.2 on 2025-11-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_alter_assinatura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('trial', 'Período de Trial'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada'), ('aguardando_pagamento', 'Aguardando Pagamento')], default='trial', max_length=20),
        ),
    ]
