# Generated by Django 5.2 on 2025-11-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_clinica'),
        ('pagamentos', '0004_alter_assinatura_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='clinica',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='organizacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_pagamento', to='accounts.organizacao'),
        ),
    ]
