# Generated by Django 5.2 on 2025-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0005_remove_assinatura_clinica_assinatura_organizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('trial', 'Período de Trial'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('expirada', 'Expirada')], default='trial', max_length=20),
        ),
    ]
