# Generated by Django 5.2 on 2025-12-01 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_clinica'),
        ('pagamentos', '0006_alter_assinatura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_pagamento', to='accounts.organizacao'),
        ),
    ]
