# Generated by Django 5.2 on 2025-12-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0007_alter_assinatura_organizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='bandeira_cartao',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='cartao_token',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='ultimos_digitos',
        ),
    ]
