# Generated by Django 5.2 on 2026-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0008_remove_assinatura_bandeira_cartao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planopagamento',
            name='tipo',
            field=models.CharField(choices=[('starter', 'Starter - Autônomos'), ('professional', 'Professional - Clínicas'), ('clinic', 'Clinic - Redes'), ('mensal', 'Mensal'), ('anual', 'Anual')], max_length=20, unique=True),
        ),
    ]
