# Generated by Django 5.2 on 2025-12-04 15:04

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolíticaRetencaoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CREATE', '🆕 Criação'), ('READ', '👁️ Leitura'), ('UPDATE', '✏️ Atualização'), ('DELETE', '🗑️ Exclusão'), ('LOGIN', '🔐 Login'), ('LOGOUT', '🚪 Logout'), ('EXPORT', '📥 Export de Dados'), ('IMPORT', '📤 Import de Dados'), ('PERMISSAO_NEGADA', '❌ Acesso Negado')], max_length=20, unique=True)),
                ('dias_retencao', models.IntegerField(help_text='Número de dias para manter o log')),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Política de Retenção',
                'verbose_name_plural': 'Políticas de Retenção',
            },
        ),
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DADOS_PESSOAIS', 'Coleta de Dados Pessoais'), ('DADOS_SAUDE', 'Coleta de Dados de Saúde'), ('MARKETING', 'Comunicações de Marketing'), ('COOKIES', 'Cookies e Rastreamento'), ('EXPORT_DADOS', 'Export de Dados Pessoais')], max_length=50)),
                ('descricao', models.TextField(help_text='Descrição clara do consentimento')),
                ('consentido', models.BooleanField(default=False)),
                ('data_consentimento', models.DateTimeField(auto_now_add=True)),
                ('data_revogacao', models.DateTimeField(blank=True, null=True)),
                ('ip_consentimento', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_lgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Consentimentos',
                'ordering': ['-data_consentimento'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', '🆕 Criação'), ('READ', '👁️ Leitura'), ('UPDATE', '✏️ Atualização'), ('DELETE', '🗑️ Exclusão'), ('LOGIN', '🔐 Login'), ('LOGOUT', '🚪 Logout'), ('EXPORT', '📥 Export de Dados'), ('IMPORT', '📤 Import de Dados'), ('PERMISSAO_NEGADA', '❌ Acesso Negado')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('dados_antes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('dados_depois', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contem_dado_sensivel', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('SAUDE', 'Dados de Saúde'), ('FINANCEIRO', 'Dados Financeiros'), ('LOCALIZACAO', 'Localização'), ('BIOMETRIA', 'Biometria')], max_length=20, null=True)),
                ('data_retencao', models.DateTimeField(blank=True, help_text='Data até quando o log será mantido (LGPD Art. 16)', null=True)),
                ('removido', models.BooleanField(default=False, help_text='Log anonimizado/removido (direito ao esquecimento)')),
                ('hash_integridade', models.CharField(max_length=64, unique=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
                ('consentimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='auditoria.consentimento')),
            ],
            options={
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioAcessoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('acessos_registrados', models.IntegerField()),
                ('hash_integridade', models.CharField(max_length=64, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.AddIndex(
            model_name='consentimento',
            index=models.Index(fields=['usuario', 'tipo'], name='auditoria_c_usuario_2cf67c_idx'),
        ),
        migrations.AddIndex(
            model_name='consentimento',
            index=models.Index(fields=['data_consentimento'], name='auditoria_c_data_co_68dbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['usuario', 'timestamp'], name='auditoria_a_usuario_ac389b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['modelo', 'objeto_id'], name='auditoria_a_modelo_3fe6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['acao', 'timestamp'], name='auditoria_a_acao_c6bf54_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='auditoria_a_ip_addr_bb42ca_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['data_retencao'], name='auditoria_a_data_re_15d34a_idx'),
        ),
        migrations.AddIndex(
            model_name='relatorioacessodados',
            index=models.Index(fields=['usuario', 'data_geracao'], name='auditoria_r_usuario_f42fd8_idx'),
        ),
    ]
