# Generated by Django 5.2 on 2025-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='hash_integridade',
            field=models.CharField(max_length=64),
        ),
    ]
