"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import os
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()  # isso vai carregar o .env automaticamente


# TOKENS DE API'S
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

# 🔑 Credenciais da API Strava
STRAVA_CLIENT_ID = os.getenv("STRAVA_CLIENT_ID")
STRAVA_CLIENT_SECRET = os.getenv("STRAVA_CLIENT_SECRET")
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")
SITE_ID = int(os.getenv("SITE_ID", 1))

#CREDENCIAIS DE ENCRIPTAÇÃO:
FIELD_ENCRYPTION_KEY = os.environ.get("ENCRYPTED_FIELDS_KEY").encode()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'chave_de_desenvolvimento_insegura')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1', '.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_filters',
    'debug_toolbar',



    # Allauth
    #'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
    #'allauth.socialaccount.providers.google',

    # Django REST
    'rest_framework',
    'rest_framework.authtoken',

    # dj-rest-auth
    #'dj_rest_auth',
    #'dj_rest_auth.registration',

    # Apps do projeto
    'corsheaders',
    'accounts',
    'api',
    'orientacoes',
    'eventos',
    'financeiro.apps.FinanceiroConfig',
    'agenteIA',
    'integracoes',
    'pagamentos',
    'auditoria',  # 🔐 LGPD Auditoria
]

#ACCOUNT_USER_MODEL_USERNAME_FIELD = None
#ACCOUNT_USERNAME_REQUIRED = False
#ACCOUNT_EMAIL_REQUIRED = True
#ACCOUNT_AUTHENTICATION_METHOD = 'email'
#ACCOUNT_EMAIL_VERIFICATION = 'optional'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    # 'allauth.account.auth_backends.AuthenticationBackend',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SITE_ID = 1

#ACCOUNT_USER_MODEL_USERNAME_FIELD = None
#ACCOUNT_USERNAME_REQUIRED = False
#ACCOUNT_EMAIL_REQUIRED = True
#ACCOUNT_AUTHENTICATION_METHOD = 'email'

#SOCIALACCOUNT_PROVIDERS = {
    #'google': {
        #'SCOPE': ['profile', 'email'],
        #'AUTH_PARAMS': {'access_type': 'online'},
        # 'APP': {
        #     'client_id': config('SOCIAL_AUTH_GOOGLE_CLIENT_ID'),
        #     'secret': config('SOCIAL_AUTH_GOOGLE_SECRET'),
        #     'key': ''
        # },
    #}
#}

# Opcional: configure o tempo de expiração do token
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    
    # 🔥 SEUS NOVOS MIDDLEWARES - DEPOIS da autenticação
    'accounts.middleware.TrialExpirationMiddleware',    # 1º - Expira trials
    'accounts.middleware.TrialAccessMiddleware',        # 2º - Bloqueia acesso
    'auditoria.middleware.AuditoriaMiddleware',         # 🔐 LGPD - Auditoria geral
    'auditoria.middleware.AuditoriaBearerTokenMiddleware',  # 🔐 LGPD - Token tracking
]

INTERNAL_IPS = [
    "127.0.0.1",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # 🔹 Muda para INFO (por padrão vem WARNING)
    },
}

CORS_ALLOW_ALL_ORIGINS = True  # Apenas para desenvolvimento

DJOSER = {
    'LOGIN_FIELD': 'email',

    'SERIALIZERS': {
        'user_create': 'accounts.serializers.CustomUserCreateSerializer',
        'user': 'accounts.serializers.CustomUserSerializer',
        'current_user': 'accounts.serializers.CustomUserSerializer',
    },
     'PERMISSIONS': {
        'user_create': ['rest_framework.permissions.AllowAny'],  # libera criar usuário
        'user': ['rest_framework.permissions.IsAuthenticated'], # perfil do usuário autenticado
        # outras permissões...
    },
}


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'backend', 'templates')],  # 👈 adicione isso
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=60,
        ssl_require=True
    )
}

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


FRONTEND_URL = os.getenv("FRONTEND_URL")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'accounts.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
