"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
from datetime import timedelta
import os
from decouple import config
import dj_database_url
from dotenv import load_dotenv

# ============================================================================
# 1. CONFIGURAÇÕES INICIAIS E AMBIENTE
# ============================================================================

# Carregar variáveis de ambiente
load_dotenv()

# Diretório base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# 2. CONFIGURAÇÕES DE SEGURANÇA
# ============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'chave_de_desenvolvimento_insegura')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1', '.ngrok-free.app']

# ============================================================================
# 3. CONFIGURAÇÕES DE APLICAÇÃO
# ============================================================================

INSTALLED_APPS = [
    # Django Core Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third-party Apps
    'django_filters',
    'debug_toolbar',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    
    # Allauth (Comentado por enquanto)
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',
    
    # dj-rest-auth (Comentado por enquanto)
    # 'dj_rest_auth',
    # 'dj_rest_auth.registration',
    
    # Project Apps
    'accounts',
    'api',
    'orientacoes',
    'eventos',
    'financeiro.apps.FinanceiroConfig',
    'agenteIA',
    'integracoes',
    'pagamentos',
    'auditoria',  # 🔐 LGPD Auditoria
]

# ============================================================================
# 4. MIDDLEWARE
# ============================================================================

MIDDLEWARE = [
    # Django Security & Core
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # CORS
    'corsheaders.middleware.CorsMiddleware',
    
    # Django Core
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Third-party
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
    
    # Custom Middleware
    'accounts.middleware.TrialExpirationMiddleware',    # 1º - Expira trials
    'accounts.middleware.TrialAccessMiddleware',        # 2º - Bloqueia acesso
    'auditoria.middleware.AuditoriaMiddleware',         # 🔐 LGPD - Auditoria geral
    'auditoria.middleware.AuditoriaBearerTokenMiddleware',  # 🔐 LGPD - Token tracking
]

# ============================================================================
# 5. TEMPLATES & URLS
# ============================================================================

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'backend', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# ============================================================================
# 6. BANCO DE DADOS
# ============================================================================

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=60,
        ssl_require=True
    )
}

# ============================================================================
# 7. AUTENTICAÇÃO & AUTORIZAÇÃO
# ============================================================================

# Modelo de usuário customizado
AUTH_USER_MODEL = 'accounts.CustomUser'

# Backends de autenticação
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    # 'allauth.account.auth_backends.AuthenticationBackend',
)

# Configurações Allauth (Comentadas por enquanto)
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
# ACCOUNT_EMAIL_VERIFICATION = 'optional'

# Validação de senha
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================================================
# 8. DJANGO REST FRAMEWORK
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# Configurações Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

# Configurações Djoser
DJOSER = {
    'LOGIN_FIELD': 'email',
    'SERIALIZERS': {
        'user_create': 'accounts.serializers.CustomUserCreateSerializer',
        'user': 'accounts.serializers.CustomUserSerializer',
        'current_user': 'accounts.serializers.CustomUserSerializer',
    },
    'PERMISSIONS': {
        'user_create': ['rest_framework.permissions.AllowAny'],
        'user': ['rest_framework.permissions.IsAuthenticated'],
    },
}

# ============================================================================
# 9. CONFIGURAÇÕES DE INTEGRAÇÃO
# ============================================================================

# URLs de frontend/backend
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")
FRONTEND_URL = os.getenv("FRONTEND_URL")

# Site ID para Django Sites
SITE_ID = int(os.getenv("SITE_ID", 1))

# 🔑 Credenciais de APIs
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
STRAVA_CLIENT_ID = os.getenv("STRAVA_CLIENT_ID")
STRAVA_CLIENT_SECRET = os.getenv("STRAVA_CLIENT_SECRET")

# 🔒 Chave de criptografia para campos
FIELD_ENCRYPTION_KEY = os.environ.get("ENCRYPTED_FIELDS_KEY", "").encode()

# ============================================================================
# 10. CONFIGURAÇÕES CORS
# ============================================================================

# Apenas para desenvolvimento - restringir em produção
CORS_ALLOW_ALL_ORIGINS = True

# ============================================================================
# 11. ARQUIVOS ESTÁTICOS E MÍDIA
# ============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ============================================================================
# 12. INTERNACIONALIZAÇÃO
# ============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================================================
# 13. LOGGING
# ============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # 🔹 Muda para INFO (por padrão vem WARNING)
    },
}

# ============================================================================
# 14. CONFIGURAÇÕES DE DEPURAÇÃO
# ============================================================================

INTERNAL_IPS = [
    "127.0.0.1",
]

# ============================================================================
# 15. CONFIGURAÇÕES DE PROVIDERS SOCIALAUTH (EXEMPLO)
# ============================================================================

# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': ['profile', 'email'],
#         'AUTH_PARAMS': {'access_type': 'online'},
#         # 'APP': {
#         #     'client_id': config('SOCIAL_AUTH_GOOGLE_CLIENT_ID'),
#         #     'secret': config('SOCIAL_AUTH_GOOGLE_SECRET'),
#         #     'key': ''
#         # },
#     }
# }

# ============================================================================
# 16. CONFIGURAÇÃO DEFAULT
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'