# Generated by Django 5.2 on 2025-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('ia_ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('resposta', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ia_ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
