# Generated by Django 5.2 on 2025-08-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Teste',
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuário',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereço', models.CharField(blank=True, max_length=255, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='api.pasta')),
            ],
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=50)),
                ('repeticoes', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='api.secao')),
            ],
        ),
        migrations.CreateModel(
            name='TodosTestes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoriateste')),
            ],
            options={
                'verbose_name': 'Todos os Teste',
            },
        ),
        migrations.CreateModel(
            name='TesteFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todostestes')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdetestes', to='api.usuário')),
            ],
            options={
                'verbose_name': 'Teste de Função',
                'verbose_name_plural': 'Testes de Função',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='TesteDor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('resultado', models.CharField(max_length=100, verbose_name='Resultado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todostestes')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdeteste_dor', to='api.usuário')),
            ],
            options={
                'verbose_name': 'Teste de Dor',
                'verbose_name_plural': 'Testes de Dor',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='api.usuário')),
            ],
        ),
        migrations.AddField(
            model_name='pasta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuário'),
        ),
        migrations.CreateModel(
            name='Mobilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilidades', to='api.todostestes')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilidades', to='api.usuário')),
            ],
            options={
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='ForcaMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('movimento_forca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forcas_musculares', to='api.todostestes', verbose_name='Movimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdeforcamuscular', to='api.usuário')),
            ],
            options={
                'verbose_name': 'Força Muscular',
                'verbose_name_plural': 'Forças Musculares',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('repetir', models.BooleanField(default=False)),
                ('frequencia', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='nenhuma', max_length=20)),
                ('repeticoes', models.PositiveIntegerField(blank=True, null=True)),
                ('evento_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='api.evento')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Estabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('resultado_unico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('movimento_estabilidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estabilidades', to='api.todostestes', verbose_name='Movimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdeestabilidade', to='api.usuário')),
            ],
            options={
                'verbose_name': 'Estabilidade',
                'verbose_name_plural': 'Estabilidades',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_html', models.TextField()),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuário')),
            ],
        ),
    ]
