# Generated by Django 5.2.4 on 2025-07-06 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcaMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musculatura', models.CharField(max_length=100, verbose_name='Musculatura')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdeforcamuscular', to='api.usuário')),
            ],
            options={
                'verbose_name': 'Força Muscular',
                'verbose_name_plural': 'Forças Musculares',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Mobilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Mobilidade')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilidades', to='api.usuário')),
            ],
            options={
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
