# Generated by Django 5.2 on 2025-08-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='secao',
            name='pasta',
        ),
        migrations.AlterModelOptions(
            name='preavaliacao',
            options={'verbose_name': 'Pré-Avaliação', 'verbose_name_plural': 'Pré-Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='sessao',
            options={'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
        migrations.DeleteModel(
            name='Orientacao',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Secao',
        ),
    ]
