# Generated by Django 5.2.4 on 2025-07-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_forcamuscular_mobilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Teste',
            },
        ),
        migrations.CreateModel(
            name='TodosTestes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoriateste')),
            ],
            options={
                'verbose_name': 'Todos os Teste',
            },
        ),
        migrations.CreateModel(
            name='TesteFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdetestes', to='api.usuário')),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todostestes')),
            ],
            options={
                'verbose_name': 'Teste de Função',
                'verbose_name_plural': 'Testes de Função',
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
