# Generated by Django 5.2 on 2025-10-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuário_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuário',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
