# Generated by Django 5.2.4 on 2025-07-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_anamnese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='data_avaliacao',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
