# Generated by Django 5.2.4 on 2025-07-12 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_anamnese_data_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='api.pasta')),
            ],
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=50)),
                ('repeticoes', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='api.secao')),
            ],
        ),
    ]
