# Generated by Django 5.2 on 2025-11-14 22:02

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_usuário_endereço_usuário_bairro_usuário_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuário',
            name='bairro',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='cep',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='cidade',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='complemento',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='data_de_nascimento',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='estado',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='numero',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='rua',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='telefone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
