# Generated by Django 5.2 on 2025-11-14 22:09

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuário_bairro_alter_usuário_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='conteudo_html',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
