# Generated by Django 5.2.4 on 2025-07-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pasta_secao_orientacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuário'),
            preserve_default=False,
        ),
    ]
