# Generated by Django 5.2 on 2025-11-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clinica_complemento_clinica_numero'),
        ('api', '0010_dataaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuário',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clinica'),
        ),
    ]
