# Generated by Django 5.2 on 2025-11-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usuário_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuário',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
