# Generated by Django 5.2.4 on 2025-07-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_evento_lembretes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.usuário'),
        ),
    ]
