# Generated by Django 5.2 on 2025-11-17 17:13

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_usuário_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuário',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, null=True, unique=True),
        ),
    ]
