# Generated by Django 5.2 on 2025-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sessao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
