# Generated by Django 5.2 on 2025-11-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usuário_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuário',
            name='email_claro',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
