# Generated by Django 5.2 on 2025-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usuário_email_claro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuário',
            name='email_claro',
        ),
        migrations.AlterField(
            model_name='usuário',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
