# Generated by Django 5.2 on 2025-08-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_sessao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilidade',
            name='nome_novo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilidades', to='api.todostestes'),
        ),
    ]
