# Generated by Django 5.2 on 2025-11-17 17:16

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_usuário_email_claro_alter_usuário_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuário',
            name='email_claro',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuário',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, null=True, unique=True),
        ),
    ]
