# Generated by Django 5.2 on 2025-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mobilidade_nome_novo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilidade',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobilidade'),
        ),
    ]
