# Generated by Django 5.2 on 2025-08-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_mobilidade_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilidade',
            name='nome_novo',
        ),
        migrations.AlterField(
            model_name='mobilidade',
            name='nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilidades', to='api.todostestes'),
        ),
    ]
