# Generated by Django 5.2 on 2025-11-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_usuário_email_claro_alter_usuário_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuário',
            name='email',
        ),
    ]
