# Generated by Django 5.2 on 2025-11-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_usuário_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuário',
            old_name='email_claro',
            new_name='email',
        ),
    ]
