# Generated by Django 5.2 on 2025-08-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_mobilidade_nome_novo_alter_mobilidade_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcamuscular',
            name='movimento_musculatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forcas_musculares', to='api.todostestes'),
        ),
        migrations.AlterField(
            model_name='mobilidade',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
