# Generated by Django 5.2 on 2025-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_forcamuscular_movimento_musculatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcamuscular',
            name='musculatura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Musculatura'),
        ),
    ]
