# Generated by Django 5.2 on 2025-11-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_organizacao'),
        ('api', '0019_preavaliacao_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuário',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organizacao'),
        ),
    ]
