# Generated by Django 5.2 on 2025-08-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_forcamuscular_musculatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forcamuscular',
            old_name='movimento_musculatura',
            new_name='movimento_forca',
        ),
        migrations.RemoveField(
            model_name='forcamuscular',
            name='musculatura',
        ),
    ]
