# Generated by Django 5.2 on 2025-08-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_movimento_musculatura_forcamuscular_movimento_forca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcamuscular',
            name='movimento_forca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forcas_musculares', to='api.todostestes', verbose_name='Movimento'),
        ),
        migrations.CreateModel(
            name='Estabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('resultado_unico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('movimento_estabilidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estabilidades', to='api.todostestes', verbose_name='Movimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdeestabilidade', to='api.usuário')),
            ],
            options={
                'verbose_name': 'Estabilidade',
                'verbose_name_plural': 'Estabilidades',
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
