# Generated by Django 5.2 on 2025-11-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_clinica'),
        ('api', '0020_usuário_organizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preavaliacao',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='usuário',
            name='clinica',
        ),
        migrations.AddField(
            model_name='preavaliacao',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organizacao'),
        ),
    ]
