# Generated by Django 5.2 on 2025-12-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_preavaliacao_clinica_remove_usuário_clinica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IADataUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kb', to='api.usuário')),
            ],
        ),
    ]
