# Generated by Django 5.2 on 2025-12-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_iadatausuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iadatausuario',
            old_name='usuario',
            new_name='paciente',
        ),
    ]
