# Generated by Django 5.2 on 2025-11-15 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('termo_uso', 'Termo de Uso'), ('politica_privacidade', 'Política de Privacidade'), ('consentimento', 'Consentimento')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('conteudo', models.TextField()),
                ('versao', models.CharField(max_length=10)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador da Clínica'), ('profissional', 'Profissional'), ('paciente', 'Paciente')], default='paciente', max_length=20),
        ),
        migrations.CreateModel(
            name='AceiteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aceite', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.documentolegal')),
            ],
            options={
                'unique_together': {('usuario', 'documento')},
            },
        ),
    ]
