# Generated by Django 5.2 on 2025-11-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_documentolegal_alter_customuser_role_aceitedocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinicas/logos/')),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='documentolegal',
            name='publico',
            field=models.CharField(choices=[('clinica', 'Clínica'), ('profissional', 'Profissional'), ('paciente', 'Paciente'), ('geral', 'Todos')], default='geral', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='accounts.clinica'),
        ),
    ]
