# Generated by Django 5.2 on 2025-11-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clinica_documentolegal_publico_customuser_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinica',
            name='numero',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
