# Generated by Django 5.2 on 2025-11-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clinica_complemento_clinica_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_google',
            field=models.URLField(blank=True, null=True),
        ),
    ]
