# Generated by Django 5.2 on 2025-11-22 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_photo_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('starter', 'Starter - Autônomos'), ('professional', 'Professional - Clínicas'), ('clinic', 'Clinic - Redes')], max_length=20, unique=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('max_pacientes', models.IntegerField()),
                ('max_usuarios', models.IntegerField()),
                ('max_avaliacoes_mes', models.IntegerField(blank=True, null=True)),
                ('recursos', models.JSONField(default=dict, help_text='Recursos disponíveis no plano')),
                ('dias_trial', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim_trial', models.DateTimeField(blank=True, null=True)),
                ('data_proximo_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('trial', 'Período de Trial'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='trial', max_length=20)),
                ('pacientes_cadastrados', models.IntegerField(default=0)),
                ('avaliacoes_mes', models.IntegerField(default=0)),
                ('ultimo_reset_uso', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='accounts.clinica')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
