# Generated by Django 5.2 on 2025-11-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_plano_assinatura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assinatura',
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
