# Generated by Django 5.2 on 2025-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_assinatura_delete_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
