# Generated by Django 5.2 on 2025-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clinica_asaas_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='credit_card_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
