# Generated by Django 5.2 on 2025-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clinica_credit_card_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_pessoa', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2)),
                ('tipo', models.CharField(choices=[('clinica', 'Clínica'), ('consultorio', 'Consultório'), ('estudio', 'Estúdio'), ('autonomo', 'Profissional Autônomo'), ('online', 'Serviço Online'), ('instituto', 'Empresa/Instituto'), ('outro', 'Outro')], default='autonomo', max_length=20)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_card_token', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizacoes/logos/')),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
