# Generated by Django 5.2 on 2025-11-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioOrganizacao', to='accounts.organizacao'),
        ),
    ]
