# Generated by Django 5.2 on 2025-11-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_organizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clinica',
        ),
    ]
