# Generated by Django 5.2 on 2025-11-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_clinica'),
        ('api', '0021_remove_preavaliacao_clinica_remove_usuário_clinica_and_more'),
        ('eventos', '0005_remove_eventoagenda_clinica_eventoagenda_organizacao'),
        ('pagamentos', '0005_remove_assinatura_clinica_assinatura_organizacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinica',
        ),
    ]
