# Generated by Django 5.2 on 2026-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_address_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizacoes/'),
        ),
    ]
