# Generated by Django 5.2 on 2025-08-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_remove_pasta_paciente_remove_secao_pasta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancodeExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Banco de Exercício',
                'verbose_name_plural': 'Bancos de Exercício',
            },
        ),
        migrations.CreateModel(
            name='ExercicioPrescrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_planejadas', models.PositiveIntegerField(default=1)),
                ('repeticoes_planejadas', models.PositiveIntegerField(default=0)),
                ('carga_planejada', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('orientacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacoes.bancodeexercicio')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpe', models.IntegerField(blank=True, null=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacoes.exercicioprescrito')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='orientacoes.pasta')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
            },
        ),
        migrations.CreateModel(
            name='SerieRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('repeticoes', models.PositiveIntegerField(blank=True, null=True)),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='orientacoes.exercicioexecutado')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacoes.exercicioprescrito')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='orientacoes.secao')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
            },
        ),
        migrations.AddField(
            model_name='exercicioprescrito',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='orientacoes.treino'),
        ),
        migrations.CreateModel(
            name='TreinoExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tempo_total', models.PositiveIntegerField(default=0)),
                ('finalizado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuário')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='orientacoes.treino')),
            ],
        ),
        migrations.AddField(
            model_name='exercicioexecutado',
            name='treino_executado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='orientacoes.treinoexecutado'),
        ),
    ]
