# Generated by Django 5.2 on 2025-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicioprescrito',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
