# Generated by Django 5.2 on 2025-10-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_alter_usuário_user'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_servico', models.CharField(default='Consulta, Liberação', max_length=100)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido')], default='pendente', max_length=20)),
                ('status_nf', models.CharField(choices=[('nao_emitida', 'Não Emitida'), ('emitida', 'Emitida')], default='nao_emitida', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lancamento', to='eventos.eventoagenda')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='api.usuário')),
            ],
        ),
    ]
