# Generated by Django 5.2 on 2025-10-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo_servico',
            field=models.CharField(default='Consulta', max_length=100),
        ),
    ]
