# Generated by Django 5.2 on 2025-10-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuário_email'),
        ('eventos', '0002_alter_eventoagenda_status'),
        ('financeiro', '0002_alter_lancamentofinanceiro_tipo_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_total', models.PositiveIntegerField()),
                ('quantidade_usada', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuário')),
            ],
        ),
        migrations.CreateModel(
            name='UsoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.eventoagenda')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.pacotesessao')),
            ],
        ),
    ]
