# Generated by Django 5.2 on 2025-10-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_pacotesessao_usosessao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacotesessao',
            old_name='data_compra',
            new_name='data_pagamento',
        ),
    ]
