# Generated by Django 5.2 on 2025-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_rename_data_compra_pacotesessao_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacotesessao',
            name='status_nf',
            field=models.CharField(choices=[('nao_emitida', 'Não Emitida'), ('emitida', 'Emitida'), ('nao_se_aplica', 'Não se aplica')], default='nao_emitida', max_length=20),
        ),
    ]
