# Generated by Django 5.2 on 2025-10-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_pacotesessao_status_nf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsoSessao',
        ),
    ]
