# Generated by Django 5.2 on 2025-10-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuário_email'),
        ('financeiro', '0006_delete_usosessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancodeAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.PositiveIntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banco_atendimento', to='api.usuário')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='financeiro.bancodeatendimento')),
            ],
        ),
        migrations.DeleteModel(
            name='PacoteSessao',
        ),
    ]
