# Generated by Django 5.2 on 2025-10-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_bancodeatendimento_transacaosessao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransacaoSessao',
            new_name='TransacaoAtendimento',
        ),
    ]
