# Generated by Django 5.2 on 2025-10-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_rename_transacaosessao_transacaoatendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancodeatendimento',
            name='saldo_atual',
            field=models.IntegerField(default=0),
        ),
    ]
