# Generated by Django 5.2 on 2025-10-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuário_email'),
        ('financeiro', '0009_alter_bancodeatendimento_saldo_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoatendimento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_atendimento', to='api.usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacaoatendimento',
            name='saldo_resultante',
            field=models.IntegerField(default=0),
        ),
    ]
