# Generated by Django 5.2 on 2025-10-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_transacaoatendimento_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaoatendimento',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='financeiro.bancodeatendimento'),
        ),
    ]
