# Generated by Django 5.2 on 2025-10-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_alter_transacaoatendimento_banco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacaoatendimento',
            name='saldo_resultante',
        ),
    ]
