# Generated by Django 5.2 on 2025-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_remove_transacaoatendimento_saldo_resultante'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoatendimento',
            name='status_nota',
            field=models.BooleanField(default=False),
        ),
    ]
