# Generated by Django 5.2 on 2025-10-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_transacaoatendimento_status_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoatendimento',
            name='saldo_resultante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transacaoatendimento',
            name='banco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='financeiro.bancodeatendimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacaoatendimento',
            name='status_nota',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida'), ('cancelada', 'Cancelada')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='transacaoatendimento',
            name='tipo',
            field=models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('pix', 'PIX')], max_length=10),
        ),
    ]
