# Generated by Django 5.2 on 2025-10-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_transacaoatendimento_saldo_resultante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacaoatendimento',
            name='saldo_resultante',
        ),
    ]
