# Generated by Django 5.2 on 2025-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_remove_transacaoatendimento_saldo_resultante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaoatendimento',
            name='tipo',
            field=models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10),
        ),
    ]
