# Generated by Django 5.2 on 2025-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_alter_transacaoatendimento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoatendimento',
            name='num_atendimentos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transacaoatendimento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
