# Generated by Django 5.2 on 2025-10-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_transacaoatendimento_num_atendimentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacaoatendimento',
            name='quantidade',
        ),
    ]
