# Generated by Django 5.2 on 2025-10-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_remove_transacaoatendimento_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoatendimento',
            name='is_reversao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transacaoatendimento',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='transacaoatendimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
