# Generated by Django 5.2 on 2025-10-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuário_email'),
        ('financeiro', '0020_alter_transacaoatendimento_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_atendimentos', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('estornado', 'Estornado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.bancodeatendimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuário')),
            ],
        ),
        migrations.DeleteModel(
            name='TransacaoAtendimento',
        ),
    ]
