# Generated by Django 5.2 on 2025-10-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuário_email'),
        ('eventos', '0002_alter_eventoagenda_status'),
        ('financeiro', '0021_transacaofinanceira_delete_transacaoatendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('num_atendimentos', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('is_reversao', models.BooleanField(default=False)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.bancodeatendimento')),
                ('evento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.eventoagenda')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuário')),
            ],
        ),
    ]
