# Generated by Django 5.2 on 2025-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_transacaooperacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaofinanceira',
            name='tipo',
            field=models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
