# Generated by Django 5.2 on 2025-10-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0023_transacaofinanceira_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.bancodeatendimento'),
        ),
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='status_pagamento',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('estornado', 'Estornado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
