# Generated by Django 5.2 on 2025-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaaccount',
            name='athlete_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stravaaccount',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
