# Generated by Django 5.2 on 2025-11-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_stravaaccount_athlete_name_stravaaccount_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stravaaccount',
            old_name='athlete_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='stravaaccount',
            old_name='profile_pic',
            new_name='profile_url',
        ),
        migrations.AddField(
            model_name='stravaaccount',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stravaaccount',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stravaaccount',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
