# Generated by Django 5.2 on 2025-12-02 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0003_rename_athlete_name_stravaaccount_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strava_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stravaaccount',
            name='strava_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE integracoes_stravaaccount
            ALTER COLUMN token_expires_at 
            TYPE integer
            USING extract(epoch FROM token_expires_at);
            """
        ),
        migrations.AlterField(
            model_name='stravaaccount',
            name='token_expires_at',
            field=models.IntegerField(),
        ),
    ]
