# Generated by Django 5.2 on 2026-01-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='data_primeiro_contato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='data_ultima_sessao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='data_ultimo_contato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status_relacional',
            field=models.CharField(default='contato', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(default='Google', max_length=50),
        ),
    ]
