# Generated by Django 5.2 on 2026-01-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_contact_options_contact_data_primeiro_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoPlanejada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensagem', 'Mensagem'), ('ligacao', 'Ligação'), ('retorno', 'Retorno'), ('avaliacao', 'Avaliação')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_planejada', models.DateTimeField()),
                ('concluida', models.BooleanField(default=False)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_planejadas', to='crm.contact')),
            ],
            options={
                'ordering': ['data_planejada'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensagem', 'Mensagem'), ('ligacao', 'Ligação'), ('atendimento', 'Atendimento'), ('avaliacao', 'Avaliação')], max_length=20)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='crm.contact')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
