# Generated by Django 5.2 on 2026-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_acaoplanejada_interacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
